#@formatter:off
version = 1

[[analyzers]]
name = "python"
dependency_file_paths = ["pyproject.toml"]

    [analyzers.meta]
    runtime_version = "3.x.x"
    type_checker = "mypy"
    additional_builtins = ["_", "pretty_output"]

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"