name: Visualizr
services:
  visualizr:
    image: ghcr.io/alphaspheredotai/visualizr:latest
    ports:
      - "7860:7860"
    volumes:
      - assets:/home/nonroot/assets
      - checkpoint:/home/nonroot/ckpts
    post_start:
      - command: chown -R nonroot:nonroot /home/nonroot
        user: root
    restart: on-failure:3
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "-f"
        - "http://localhost:7860"
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
      start_interval: 5s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
volumes:
  checkpoint:
    name: Checkpoint of AniTalker
  assets:
    name: Assets of Visualizr
