[project]
name = "visualizr"
version = "0.1.0"
description = "Video Generator part of the Chatacter Backend"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "pyrefly>=0.16.1",
    "ruff>=0.11.10",
    "ty>=0.0.1a6",
]
