name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  actions: read
jobs:
  test:
    name: ${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - pre-commit
          - lint
    steps:
      - uses: AlphaSphereDotAI/helpr_action@main
        with:
          is_test: true
          lint: true
          linter: ${{ matrix.linter }}
          github_token: ${{ secrets.GH_TOKEN }}
