name: Trunk Code Quality
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  checks: write # For trunk to post annotations
  contents: read # For repo checkout
jobs:
  trunk:
    name: Trunk Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
          check-mode: populate_cache_only
