name: Trunk Code Quality
on:
  push:
  workflow_run:
    workflows: ["Pull Request"]
    types: [completed]
permissions:
  checks: write
  contents: read
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  trunk:
    name: Trunk Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Trunk Code Quality
        uses: trunk-io/trunk-action@v1
