name: Code Analysis
on:
  push:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        id: uv
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        if: steps.uv.outputs.cache-hit != 'true'
        run: uv sync --frozen
      - name: Run Ruff
        run: uv run ruff check .
  ty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        id: uv
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install the project
        if: steps.uv.outputs.cache-hit != 'true'
        run: uv sync --frozen
      - name: Analysing the code with Ty
        run: uv run ty check
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          config: ./.github/hadolint.yml
